# Generated by Django 3.0.3 on 2020-02-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200)),
                ('a_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bookwriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=20)),
                ('b_name', models.CharField(max_length=200)),
                ('b_page', models.IntegerField()),
                ('b_year', models.CharField(max_length=50)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Publisher')),
            ],
        ),
    ]
