# Generated by Django 3.0.3 on 2020-02-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='a_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='a_year',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_year',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='p_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
