# Generated by Django 3.0.3 on 2020-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20200226_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='a_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='a_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='p_name',
            field=models.CharField(max_length=200),
        ),
    ]
