# Generated by Django 3.0.3 on 2020-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20200226_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='a_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookwriter',
            name='b_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='p_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
